---
title: June 1 Example Sites
timezone: Europe/Amsterdam
collections:
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
